### ISSUE TITLE
Network Drive Fix for Docker-Compose on Win10

### ISSUE THREAD

**Issue by DevilsDesigns** [mueslimak3r/tv-intro-detection#17]
**Describe the bug**

**To Reproduce**
1. Create a docker Compose 
```
---
version: "3.8"

volumes:
  mymount:
    name: Movies4You-NAS
    driver_opts:
      type: cifs
      o: "user=Guest,iocharset=utf8,vers=3.1.1,rw"
      device: \\192.168.1.111\Jellyfin-Media\
  myothermount:
    name: Movies4You-Server
    driver_opts:
      type: cifs
      o: "user=Guest,iocharset=utf8,vers=3.1.1,rw"
      device: \\192.168.1.119\Jellyfin-Media\

services:
  Jellyfin-Intro-Scanner:
    image: ghcr.io/mueslimak3r/jellyfin-intro-scanner:latest

    container_name: Jellyfin-Intro-Scanner
    environment:
      - JELLYFIN_URL=http://192.168.1.111:8096
      - JELLYFIN_USERNAME=ADMIN
      - JELLYFIN_PASSWORD=PASSWORD
      - PATH_MAP=/mnt/Movies4You-NAS/TV-Show::/Movies4You-NAS/TV,/mnt/Movies4You-Server/TV-Show::/Movies4You-Server/TV-Show,/mnt/x/TV-Show/::/jellyfin-x/TV-Show
      # - LOG_LEVEL=DEBUG
    volumes:
      - \\192.168.1.111\Jellyfin-Media\TV-Show:/mnt/Movies4You-NAS/TV-Show
      - \\192.168.1.119\Jellyfin-Media\TV-Show:/mnt/Movies4You-Server/TV-Show
      - /c/Tools/Jellyfin-Intro-Skip/config:/app/config
    restart: unless-stopped

  Jellyfin-Intro-Skipper:
    image: ghcr.io/mueslimak3r/jellyfin-intro-skipper:latest

    container_name: Jellyfin-Intro-Skipper
    environment:
      - JELLYFIN_URL=http://192.168.1.111:8096
      - JELLYFIN_USERNAME=ADMIN
      - JELLYFIN_PASSWORD=PASSWORD
    volumes:
      - /c/Tools/Jellyfin-Intro-Skip/config:/app/config
    restart: unless-stopped
```
**Expected behavior**
Wont run a scan of intros of all media in tv shows
Network drives are in 
\\192.168.1.111\Jellyfin-Media\
 \\192.168.1.119\Jellyfin-Media\
for both network shares tv shows are in 
 \\192.168.1.111\Jellyfin-Media\TV-Show
 \\192.168.1.119\Jellyfin-Media\TV-Show
**Additional context**

**Comment by mueslimak3r** [comment]
try this and see if it works
Be aware that `o: "user=Guest,iocharset=utf8,vers=3.1.1,rw"` assumes the shares are available to guest users.

If you can't access them as guest, you can adapt the `o:` value following this example from the docker documentation:
`o=addr=192.128.1.111,username=uxxxxxxx,password=*****,file_mode=0777,dir_mode=0777`

If when you mount the network drives in windows you don't need to enter a password, then guest mode should work.


What I've included in this example for `PATH_MAP` is my best guess based on the screenshot you sent of your library settings in jellyfin since it's `what-the-container-sees::what-jellyfin-sees`

```
---
version: "3.8"

volumes:
  movies4you-nas:
    name: movies4you-nas
    driver_opts:
      type: cifs
      o: "user=Guest,iocharset=utf8,vers=3.1.1,rw"
      device: \\192.168.1.111\Jellyfin-Media\
  movies4you-server:
    name: movies4you-server
    driver_opts:
      type: cifs
      o: "user=Guest,iocharset=utf8,vers=3.1.1,rw"
      device: \\192.168.1.119\Jellyfin-Media\

services:
  Jellyfin-Intro-Scanner:
    image: ghcr.io/mueslimak3r/jellyfin-intro-scanner:latest

    container_name: Jellyfin-Intro-Scanner
    environment:
      - JELLYFIN_URL=http://192.168.1.111:8096
      - JELLYFIN_USERNAME=ADMIN
      - JELLYFIN_PASSWORD=PASSWORD
      - PATH_MAP=/mnt/movies4you-nas/TV-Show::J:\TV-Show,/mnt/movies4you-server/Jellyfin-Media/TV-Show::\\MOVIES4YOU-SERV\Jellyfin-Media\Jellyfin-Media\TV-Show
      # - LOG_LEVEL=DEBUG
    volumes:
      - movies4you-nas:/mnt/movies4you-nas
      - movies4you-server:/mnt/movies4you-server
      - /c/Tools/Jellyfin-Intro-Skip/config:/app/config
    restart: unless-stopped

  Jellyfin-Intro-Skipper:
    image: ghcr.io/mueslimak3r/jellyfin-intro-skipper:latest

    container_name: Jellyfin-Intro-Skipper
    environment:
      - JELLYFIN_URL=http://192.168.1.111:8096
      - JELLYFIN_USERNAME=ADMIN
      - JELLYFIN_PASSWORD=PASSWORD
    volumes:
      - /c/Tools/Jellyfin-Intro-Skip/config:/app/config
    restart: unless-stopped
    ```
